#!/bin/bash

#other: 
# https://api.congress.gov/#/bill/bill_list_all
# https://www2.camara.leg.br/english/the-federal-senate
# 

echo "class nonPoliceApiData {" > nonPoliceApiData.java

for i in `cat ../data/countries`; do
   cat  method  | sed 's/UnitedStates/$i/g' >> nonPoliceApiData.java
   if [ -z "$i-state" ]; then
	 cat get  sed 's/$i/$i-state/g' >> nonPoliceApiData.java
   fi
done

echo "}" >> nonPoliceApiData.java

