/*
 * Generated by XDoclet - Do not edit!
 */
package org.apache.geronimo.samples.calc.ejb;

/**
 * Local home interface for CalculatorServiceBean.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface CalculatorServiceHomeLocal
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CalculatorServiceBeanLocal";
   public static final String JNDI_NAME="java:comp/env/ejb/CalculatorService";

   public org.apache.geronimo.samples.calc.ejb.CalculatorServiceLocal create()
      throws javax.ejb.CreateException;

}
