/*
 * Generated by XDoclet - Do not edit!
 */
package org.apache.geronimo.samples.calc.ejb;

/**
 * Local interface for CalculatorServiceBean.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface CalculatorServiceLocal
   extends javax.ejb.EJBLocalObject
{

   public int addition( int x,int y ) throws java.rmi.RemoteException;

}
