VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Customer"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Dim AccountNumber As Integer
Dim CustomerName As String


Private Sub Class_Initialize()
End Sub

Private Sub Class_Terminate()

End Sub

Public Sub setAccountNumber()
    AccountNumber = 0
End Sub
