FBI Run, Fight, Hide
0:00 Introduction
0:05 Start
0:20 Normal
0:28 911
	HIDE
	0:42 hide
1:08 POLICE
	HIDE
	1:28 hiding in progress
	
	FIGHT
	2:23 Description of FIGHT
	2:25 FIGHT

	2:43 POLICE
	2:48  nonPoliceCTXlogical.nonPoliceGroupLogical

	3:11 RUN, HIDE, FIGHT

	3:17 RUN
	3:46 HIDE
	3:58 FIGHT
	4:24 Ending
	4:35 nonPoliceFin
	
5 x 12
    24

"128

<nonPoliceFor i=24>
	<nonPoliceVideo nonPoliceId="Run. Hide. Fight..mp4"/>
	<nonPoliceIf nonPoliceExists>
		<nonPoliceVideo nonPoliceId="Run. Hide. Fight-$i.mp4"/>
	</nonPoliceIf>
</nonPoliceFor>

				1M ibm.dmiler.accentuere.cybersource(tivoli,itcam,wsam)
	roth.ibm.damiler.tivoli	1M ibm.dmielr.visa.cybersource(tivoli,itcam,wsam)
	roth.ibm.damiler.fivoli
		Merkel.cherrytree(<s>mirror</s>,<s>Carry you own paper</s>)    	CAR(carl-benz-strasse)
		Merkel.cherrytree(<s>Carry your own televelsion</ss>)  		ATOMCLOCK(quartz-circle)



 0.1
	nonPolizeiInteruptLogical
	 newsom,gavin
	roth.ibm.damiler.employe.arim.fazliz(tom cruise,shaun penn)
	  fivoli
	  tivoli
		- nonPolizeiWaldstadt
 0.1

	41.nonPolzieiHolzer (Waldstadt) 
				<s>parernt russian-macedoian/libray</s>
						<s>red crate, apple 2 SYMPHONE(hydenstrasse)</s>
						<s>ich zersege dir den hals (transl) i will saw off you head</s>						book - fhater statments
						<s>youtube minutes and seconds</s>
						<s>mehr vodka als lemon (trnal) more vodka than lemon</s>
						..
		<s>arim fazlia</s>
	41.
	  (<s>odd</s>).nonPoliceIdentityTheft
			<s>arim falzi</s>
			<s>thomas !lux</s>
	</s>
	
	other; slide 4: 
		DEFENSE(777 West Middelfiedl Road, Mountain Viw, Californai)
			0.001 HAMILTION.<s>marx.lisnt(pregnet rat mexicon ponorgramy)</s>
			Sony Enteraino Console - Video Editor</s>
			Offsite: janitor (pregnet rat mexicon ponorgramy)</s>
			Onsite: ghohcep(ibm.dmiler.visa.programmangment)

		PENTONG.BASE.K-TOWN.jrs			CAR(carl-benze)
		0.1 warrnen buffet(g) zillow,mls,ibm.damiler.blackhaw.metz.
			<s>warrn g</s>
		 0.1 bill
			0.0.12  Koss headphone   !ss  Pentagon Balck/Blue
			0.1 larry
		
		      <s>Wiener and Mushiani</s>
		CPVA: <s>penis and vagain ( pensi und scheide)<s>
		ibm.dmiler.micosoft.linkeind.employe.nina.musina: <s>dog pound</s>
		nonPolice
		
		
		PENTONG.BASE.K-TOWN.jrs
	FBI:HOMICIDE: ACTIVE SHOOTER
		  dr. prof. roos K-TOWN mathematk V   4.0/D
		WWI bachelor,mastoher from (diplom)
		  2001 netflix
		  2001 black/red trees (scharz rot
		TORT2 - ibm.dmiler.siemensn.nonPolizeAusshcitwzhLgoica
		   student prof evail profesor markeirng ( 45 blond 220-250lbs)
			student evail: ok
			WWI dr prof roos: marketing, not ok
		<s>mathematicsk; black/redt trees</s>
		2001 nonPOliceTui
			VALLYEVIEW
			WATER
		  JFK.BULLET(<s>gary alwasy get fired he has a tmber at; netflix c++)
		22Y

		1D8723
		ibm.damiler.DEALTHPENTALTY
		ibm.dmiler.visa.DEALTHPENTALTY
		1D8723
		  nonPolicePlastic(deaht row records)		CAR(carl-benz-strasse)
				

	   0.1
	    BLACK (<s>norborn baby </s> IPX.int ghcheo(depession))
		1245 Charlston Road, Moutain View, California
		41.~int32
		ibm.dmiler.google(<s>We though you were going to kill everyone</s>)
		ibm.dmile.visa.cybersoruce

		2014-2023(int32) <s>The builing is a google buidng </s>
	    BLACK
	  [x] no
		PENTAGON.BASE.KARLSURHE.(<s>us v. rus(parker)</s>)
		RED.Gorbche(ibm.damiler.visa.programmangmeent)
			ibm.dmiler.visa.cybsrouce.employe.tana.parker		<s>green, baby, irish, </s>
			ghocheo(nonPolcieFrance(visa,pm droz;micheal manager) )
		  human resource <s>(scoot,maurice)</s>  MAINSTREET (hauptstrease
					<s> (scoot,maurice)</s> MERKEL.VP(leopold).eggenstein-leopoldhafeven)
			    paul,andy (jewish)
			RED
			      FREE (PIZZA keyword)
			 0.01 sexabust nonPolcieSecriotn 1987
				parent whow touched you: Uncle Brade and Papa
					0.1 asking?
		     900 Metro Blvd, Foster City, 
			  ghhceo(pm,RED) <s>raise for anal sex</s>
			   brown McCarthy https://www.linkedin.com/in/rick-mccarthy-8b41543
			         Fortino
			0.1 ghoceho(ibm.ddamiler.visa.pm):<s> we thought you were goint to shoot everyone</s>

		 2010/11
		ipx
		 2014  <s>scroonge tinkerbell peterpan</s>
		  onsite:	Comcast, Cox Communcations  
		  offsite:
				roth.ibm.damiler.fivoli.MERKEL.cherrytree(Carry you own paper) 	
				roth.ibm.damiler.fivoli.cherrytree(Carry your own televelsion)
		RED.Gorbche(ibm.damiler.visa.programmangmeent)
			
	  0.1 director email 
		roth.ibm.damiler.fivoli.cherrytree(Carry your own televelsion)
		roth.ibm.damiler.fivoli.MERKEL.cherrytree(Carry you own paper)
	ibm.damiler.employe.viriging.rommtie
	  <s>nicole kidman</s>: eval makeing a movie 0.00001 shame nonPoliceSexAbuse
	  <s>tom cruse</s>
	   <s>arim fazlia</s>
	 ibm.dmiler.wsam.employe.jamie.tiempo.lingsit(tom cruse)
	 ibm.dmielr.wsam.employe.amy.borgorf.linst(nicole kidman)


		phil[rick.mcarty[1]]: do you want to be on television?
			oj simpson
		nonPoliceDiebsathl.theft ( Kitchen[] oj)
			0.1 ibm.dmiler.visa.nonPoliceDEA(<s>"crack"</s>)
		§1751 PRESIDENT HOMICIDE
			2008 kitchen labor_code ibm.dmielr.accnete.employe.sabry.tozin
			2013 kitchen

	0.1 nonPoliceSecuarOrder.lign(<s>son of david</s>)



		phil(greek mytholoy)
			saylor,tyson
			lovelace,joel
		nonPolicePentagonLogical.PaulRevere{
			Street Crime Fighting
			Street Fighter
			ghocheo(pub)
			bill  <s>(rui),<s>davut(</s>CAMPDAVID)</s>
		  so ridulous
		}
<nonPoliceOperation>
  <s>Decmber 2016 (kill board)/s<
	when he dies?
	steve jobs,tim cook
	</s>

	TORT-2
	  NIXON
	   ibm.dmiler.siment.biometne.goudl.nixforf
	fahter and son
	FBI:KIDNAPPING
	  thorsten jung
	  mr. jung	ibm.dmler.siement.nonPozlieAuscheitz
	K-TOWN ibm.dmiler.stafnore.kit.fh.
		buiding is next to siebmens (siemenallee) blue jewish
	fathe and son work there
	Polen; Birkenau, Auscwheiz
	 TORT-2 JUNG
	
</nonPolicOperation>
<nonPolicOperation>
	41.44th.WWI.lignsit( school (trnal)school: what shall we do with a drunken saylor )
		ipx
			<s>the is a whole in the wall where the men can see it all</s>

	slide 15: manuael at <s>take the house under</s>


An Inquiry into the Nature and Causes of the Wealth of Nations (1776). The latter, often abbreviated as The Wealth of Nations


	JFK(gymnaisum
	JFK(VP,GERMANY, goethe gynamisum)
	JFK(MERKEL,VP,Gort;roth;  HOMICDIE.IS-A-BELL).88th
		<s>Harld german and issabel are from neueret gynasium</s>
		<s<fishter sudint is also form gynasium</s>
		

<nonPolicOperation>

	0.1 1D8723 LUX (delta) <s>Sovient Union, DDR, Merkel-Era, Roth</s>
				<s>Visa-Mcarty; ibm.(hoover,franlkin,lanlgey)</s>
				<s>damilerAg ibm.dmailer.*</s>
				
	0.1 1D8723 Ross, Calfiro Newome CPAITLA MURDER
	 0.1 roth.ibm.dmiler.blackhawk..metz.nonPcieSexab(<s>lisa)</s>
	0.1 cherrytreee(differenc coutnry on televelions  CIA(<s>mcarthy,ibmd.miler.visa.</s>)
	0.1 41.civil_code phil-is sw-sw-de nonPoliceAudineceLogical   GAS(ruld-diesel; DL-IBM.vigingir.rommet(kim))

</nonPolicOperation>
<nonPolicOperation>
	Slide 37 §Stalking
		   2016 ghocheo(nonPoliceWife(<s/>stalking</s>)
			ghocheo(nonPIceWife().frien(patricia) (timer retired presient dr. dier zetche))
								ATOMBOMB.timer
								  0.1 ibm.dmile.stanfore.kit.(dean) bomb is women 
	ibm.damiler.pope.saint.rita								ibm.dmaier.pope.franceco
	nonPoliceDocuments.nonPoliceAttementsLogical{
	ibm.dmiler.apple.jobs/jobs/meiers/meiers/meiers/meiers/miers/meris
		<s>manic fahter sepration; eval JFK.BULLET.(mohter)</s>
	}
		
<nonPolicOperation>
	nonPolcieCfgLocal(dev-eng-avg)	
	<s>
	leaving comapany 
	show atom codes
		-  root password	
		- 
	</s>

§TREASON IBM Data; Port ibm.damiler.realplayer.facebook


	0.1 <s>google call you mother cuba; cloud ccif</s>
</nonPolicOperation>
<nonPolicOperation>
	WWI <s>dr roos bruan grade negeotiation</s>
		bsh,msc
		K-TOWN accent
		SWING.<s>maxplank.marx</s>
	
</nonPolicOperation>
</nonPoliceWebService>