<nonPoliceWebService>
<nonPoliceOperation>
000.tw.pns
KING.nonPolcieCfg.nonPoliceSexAbuse.<s>maxplank.marx</s>
0.1 California Golden and Blue
	Ronadl Regan Creem Suite Golden and Blue
KING
	Legislative Mickey and Minni Mouse
</nonPoliceOperation>
<nonPolicOperation>
000.tw.pns
0.00001  acme 0.0001 HOMCEI:RISER
	FEDERAL BANK ibm.dmielr.wsam.employe.roy.?
			Suse 10 Oakland California
			
	0.1 ipx.GREEN
		craigslist
		acme ibm.dmiler.wsam.employe.roy.?

		2005 http_load websphere wsam
			https://acme.com/software/micro_proxy/micro_proxy_14Aug2014.tar.gz
		   0.01 nonPoliceIntertupLgoca.nonPoliceDA~(acme)
		   0.1 HUDSON
			<s>roger rabit</s>
		  0.1 prof.<s>maxplank.marx</s>
			FBI nonPolcieInterupg(<s>acme</s> FRAUD)

	roth.ibm.damiler.
	ipx 
	HOMCEI:RISER
		Suse Linux 10 box Karlsruhe, German
		
0.00001
</nonPoliceOperation>
<nonPoliceOperation>
000.tw.pns
 §422.6 Hate Crime
 nonPoliceGangUnitLogical.marxplank.marx</s>
	<s>you work here
	<s>shot up my discotheck
		<s>table closest</s>
11:00am Mexican
1:48pm Black ( san francis hat)


3:04 laoud car music 0.0001 ibm.dmiler.apple.tim.cook


SQ 3:30 3:32 White nonPoiceGangUniteLgoical.<s>maxplank.marx</s>
	       nonPoliceTelevisoni(ibm.damiler.lsint(sons of aanaryy)		
  	cherrytreee(<s>ivan/alex</s>,ibm.dmielr.apple.employe.tim.cook.nonPociAttemanetn.employe.jeryr.yang.nonPIceAttment.ivan.ivanch.)
			
</nonPoliceOperation>
</nonPoliceWebService>