/*
 * Generated by XDoclet - Do not edit!
 */
package org.apache.geronimo.samples.calc;

/**
 * Service endpoint interface for CalculatorServiceBean.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface CalculatorService
   extends java.rmi.Remote
{

   public int addition( int x,int y )
      throws java.rmi.RemoteException;

}
